name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 20.4.0
        - name: Install
          run: npm install
        - name: Test
          env:
            BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
            BROWSERSTACK_PASSWORD: ${{ secrets.BROWSERSTACK_PASSWORD }}
          run: npx wdio config/wdio.browserstack-android.conf.js --spec test/specs/android-noteColor.spec.js
        - uses: actions/upload-artifact@v3
          if: failure()
          with:
            name: logs
            path: logs